---
name: security-scan

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron: "17 4 * * 1"

permissions:
  contents: read

jobs:
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run Trivy vulnerability and misconfiguration scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,misconfig,secret
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
